#!/bin/sh

# Use superior neovim
alias vim="nvim" vimdiff="nvim -d"

# Remove need for sudo in these commands
for command in pacman shutdown reboot mount umount tor systemctl visudo; do
	alias "$command"="sudo $command"
done ; unset command

# Add some color to your life
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# Shorter commands
alias \
	l='ls' \
	la='ls -la' \
	ll='ls -l' \
	ka="killall" \
	g="git" \
	e="$EDITOR" \
	v="$EDITOR" \
	es="edit-script" \
	tt="taskwarrior-tui" \
	as="add-script" \
	trr="transmission-remote" \
	td="transmission-daemon" \
	untar="tar -xvf" \
	pi="pacman -S" \
	piu="pacman -Syu" \
	ue="pacman -Syu --noconfirm && exit" \
	pr="pacman -R" \
    nc="ncmpcpp" \
    nb="newsboat" \
    dm="udisksctl mount -b" \
    dum="udisksctl unmount -b" \
    dpo="udisksctl power-off -b" \
    ts="torsocks" \
	p="pacman" \
    sctl="systemctl" \
    ud="update-dwmblocks" \
    clc="clear-clipboards"

# Main aliases
alias \
	mk='make && sudo make clean install' \
	lo='kill -9 -1' \
	mo='mk && lo' \
	monerod="monerod --data-dir $XDG_DATA_HOME/bitmonero" \
	off="shutdown -h now" \
	tst="tabbed -r2 st -w '' && exit" \
	vs="$EDITOR ~/.config/zsh/.zshrc && . ~/.config/zsh/.zshrc" \
	vp="$EDITOR ~/.config/shell/profile && head -n -1 ~/.config/shell/profile | tail -n +3 > /tmp/profile.tmp && . /tmp/profile.tmp && rm /tmp/profile.tmp" \
	va="$EDITOR $ALIASRC && . $ALIASRC" \
    bl="cat /sys/class/power_supply/BAT0/capacity" \
    lf="lfrun" \
    set-tv-output="xrandr --fb 1360x768 --output $INTERNAL_DISPLAY --off --noprimary --output $EXTERNAL_DISPLAY --mode 1360x768 --primary ; audio-output EXTERNAL_ONLY ; remaps" \
    exp="xarchiver ~/Home/Others/Archives/Black_Dog.rar" \
    autoconf="nvim ~/.local/src/autoconfig/autoconfig" \
	vimrc="$EDITOR $XDG_CONFIG_HOME/$EDITOR/init.vim" \
    hor="xdg-open /mnt/Shared/Home/GII/3º/General/Horario.pdf 2>/dev/null" \
    nstart="rfkill unblock wifi ; sudo systemctl start NetworkManager" \
    nstop="rfkill block wifi ; sudo systemctl stop NetworkManager"
