#!/bin/sh

# Use superior neovim
alias vim="nvim" vimdiff="nvim -d"

# Remove need for sudo in these commands
for command in pacman shutdown reboot mount umount tor systemctl visudo fdisk cfdisk ufw; do
    alias "$command"="sudo $command"
done ; unset command

# Shorter commands
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
  locate="locate -i" \
	l='ls' \
	la='ls -la' \
	ll='ls -l' \
  rm='rm -ri' \
  rmf='rm -rf' \
	ka="killall" \
	g="git" \
	e="$EDITOR" \
	v="$EDITOR" \
	es="edit-script" \
	tt="taskwarrior-tui" \
	trr="transmission-remote" \
	td="transmission-daemon" \
	untar="tar -xvf" \
	pi="yay -S" \
	piu="yay -Syu" \
	pr="yay -Rs" \
  nb="newsboat" \
  dm="udisksctl mount -b" \
  dum="udisksctl unmount -b" \
  dpo="udisksctl power-off -b" \
  ts="torsocks" \
	p="pacman" \
  q="exit" \
  :q="exit" \
  sctl="systemctl" \
  ud="update-dwmblocks" \
  clc="clear-clipboards" \
  mkx="chmod u+x" \
  iv="imv" \
  sv="sudo $EDITOR" \
  z="zathura" \
  ot="setsid -f $TERMINAL" \
  dr="dragon -s 40 *" \
  duh="du -hd1 . | sort -rh" \
	mk='make && sudo make clean install' \
	lo='kill -9 -1' \
	mo='mk && lo' \
	off="systemctl poweroff" \
	reboot="sudo systemctl reboot" \
  nstart="rfkill unblock wifi" \
  nstop="rfkill block wifi" \
  km="kill-matching" \

# Main aliases
alias \
  dmcd="source $(which disk-mount-cd)" \
  crontab="crontab -i" \
  hst='instr=$(fzf < "$HISTFILE") ; xdotool type "$instr" ; xdotool key Return'  \

source "$XDG_CONFIG_HOME/shell/otherAliases"
