#
# ~/.bash_profile
#


export PATH="$PATH:$HOME/.local/bin:$HOME/.local/bin/statusbar"


# Default programs
export EDITOR="vim"
export TERMINANL="st"


export HOME="/home/ache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export PHOTOS_DIR="$XDG_DATA_HOME/Pictures"
export BACKGROUND_LINK="$XDG_DATA_HOME/bg"
export LESSHISTFILE="-"
export HISTFILE="$XDG_CONFIG_HOME/shell/history"
#export GIT_CONFIG="$XDG_CONFIG_HOME/git/gitconfig"
export MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
export XAUTHORITY="$XDG_CONFIG_HOME/x11/Xauthority"
export INPUTRC="$XDG_CONFIG_HOME/inputrc"
export XDG_RUNTIME_DIR="$XDG_CACHE_HOME"
export ALIASESFILE="$XDG_CONFIG_HOME/shell/aliases"


[[ -f "$XDG_CONFIG_HOME/shell/bashrc" ]] && source "$XDG_CONFIG_HOME/shell/bashrc"

exec startx $XINITRC
