#!/bin/sh

setxkbmap -layout es

autostart="autorandr xcompmgr setbg dunst clipmenud remaps"

for prog in $autostart; do
	pidof -s "$prog" || "$prog" &
done >/dev/null 2>&1

cycle-displays "$DEFAULT_DISPLAY_PROFILE"
