#!/bin/bash


zathura_color_config() {
        zathuraconf="$XDG_CONFIG_HOME/zathura/zathurarc"
        mkdir -p "${zathuraconf%/*}"
        mv -n "$zathuraconf" "$zathuraconf.bak"
        ln -sf "$XDG_CACHE_HOME/wal/zathurarc" "$zathuraconf"
}

dunst_color_config() {
        dunstconf="$XDG_CONFIG_HOME/dunst/dunstrc"
        mkdir -p "${dunstconf%/*}"
        mv -n "$dunstconf" "$dunstconf.bak"
        ln -sf "$XDG_CACHE_HOME/wal/dunstrc" "$dunstconf"
}

fix_sequences() {
        e=$'\e'
        sequences=$(cat)
        foreground_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]10[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"
        background_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]11[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"
        cursor_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]12[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"

	for term in /dev/pts/{0..9}*; do
		echo -e "\e]4;256;${cursor_color}\a\c" > "${term}" 2>/dev/null
		echo -e "\e]4;256;${background_color}\a\c" > "${term}" 2>/dev/null
		echo -e "\e]4;259;${foreground_color}\a\c" > "${term}" 2>/dev/null
	done
}


source "$XDG_CACHE_HOME/wal/colors.sh"

#zathura_color_config
dunst_color_config

fix_sequences <"$XDG_CACHE_HOME/wal/sequences"

pkill dunst; setsid -f dunst
